dat <- plotData[plotData$Date %in% c("1/2/2007","2/2/2007"),]
dat$DateTime<-strptime(paste(dat$Date, dat$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
png(file = "plot4.png", width = 480, height = 480)
columnlines <- c("black", "red", "blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
par(mfrow=c(2,2))
plot(dat$DateTime,dat$Global_active_power,type='l',col="black",xlab = "Global Active Power(kilowatts)")
plot(dat$DateTime,dat$Voltage,type='l',col="black",xlab = "datetime",ylab="Voltage")
plot(dat$DateTime,dat$Sub_metering_1,type="l",xlab='',ylab="Energy Sub Metering",col=columnlines[1])
lines(dat$DateTime,dat$Sub_metering_2,col=columnlines[2])
lines(dat$DateTime,dat$Sub_metering_3,col=columnlines[3])
legend("topright", legend=labels, col=columnlines, lty="solid")
plot(dat$DateTime,dat$Global_reactive_power,type='l',col="black",xlab="datetime",ylab = "Global_reactive_Power")
dev.off()